### ISSUE TITLE
Impossible to hide Hero Settings panel

### ISSUE THREAD

**Issue by vadimvh** [jshimko/telescope-plugin-hero#2] opened 2015-05-24 10:57 UTC
Hi!

I run the latest versions of meteor and telescope. After installing telescope's Hero plugin via `meteor add jeremy:telescope-plugin-hero` and mounting the app locally, I can't hide the Settings panel. Looks like the small tab with the arrow doesn't work..

**Comment by jshimko** [comment] 2015-05-25 15:17
I can't reproduce your issue.  Is there any more info you can share?  Are there any errors in your browser console?  What do you get if you run `Telescope.VERSION` in the console?  Have you modified Telescope at all?  What browser/OS are you using?  Screenshot of what you're seeing?

**Comment by elvista** [comment] 2015-05-28 19:46
I have the exact issue.

Telescope.VERSION = "0.20"
Screenshot of not logged in: http://puu.sh/i3WOl/5e28e66dfc.jpg
Screenshot logged in: http://puu.sh/i3WYV/1a22aa5f85.jpg (zoomed out)

Using Windows 8 / Chrome. Have not modified Telescope (fresh install)

The CSS itself is not loading. The JS otherwise seems to be working. Perhaps the package requires a compiled CSS file? (I see the SCSS file, but no CSS)

**Comment by jshimko** [comment] 2015-05-29 18:52
Hey @elvista. The package uses [`fourseven:scss`](https://github.com/fourseven/meteor-scss) to compile the SCSS.  The problem you're experiencing is with `fourseven:scss` not working properly on Windows.  I unfortunately can't do much about that other than manually compile the SCSS and use regular CSS in my package instead.  But since I'd really prefer not to have to manually run a SCSS compiler every time I'm working on the plugin, I think we're going to have to wait for the Windows bugs to be sorted out with the SCSS package.  

Sorry I don't have a better answer.  Windows is unfortunately a hard development environment to support sometimes.  I recommend [filing an issue](https://github.com/fourseven/meteor-scss/issues) over at the `fourseven:scss` repo.  I suspect a lot of Windows users are having the same issues.  For example: https://github.com/fourseven/meteor-scss/issues/94  

Another alternative that would probably solve a ton of Windows development issues would be to run something like [Ubuntu](https://ubuntu.com) in [Virtualbox](https://www.virtualbox.org/) and then just do all of your Meteor development on Linux.  Waiting for Windows support can be a painful process sometimes.

**Comment by jshimko** [comment] 2015-06-12 02:09
Since this is an issue with fourseven:scss and Windows, I'm going to close this issue for now.  Let me know if there's anything else I can do to help.  :)

**Closed as completed by jshimko** 2015-06-12 02:09 UTC

**Comment by x5engine** [comment] 2015-06-12 02:15
Tthey must have fixed the issue though ?

**Comment by jshimko** [comment] 2015-06-12 02:16
I'm not sure.  I don't have a Windows machine with a Meteor dev environment set up.  Sorry.
