### ISSUE TITLE
Hero Header doesn't look good

### ISSUE THREAD

**Issue by x5engine** [jshimko/telescope-plugin-hero#1] opened 2015-05-16 01:47 UTC
Hi thank you for this great plugin,

I saw the demo and it's awesome,  but i couldn't get this same result on my localhost 

This is how it look like
![screenshot 2015-05-16 02 34 13](https://cloud.githubusercontent.com/assets/12363020/7664227/c3919f9a-fb75-11e4-8bc1-9629890c7424.png)

Thanks in advance

**Comment by jshimko** [comment] 2015-05-16 01:55
What browser/OS are you using?  Are you using the latest version of Telescope ([devel](https://github.com/TelescopeJS/Telescope/tree/devel) branch)?

**Comment by jshimko** [comment] 2015-05-16 01:55
That looks like tons of CSS conflicts to me.

**Comment by x5engine** [comment] 2015-05-16 01:57
Yes this is just some css conflicts but everything is working good
I'm using the latest Chrome version

**Comment by jshimko** [comment] 2015-05-16 02:13
That's actually A LOT of conflicts.  Just about every part of the plugin UI is pretty jacked up.  :)  

That's supposed to look like this:

![hero-plugin](https://cloud.githubusercontent.com/assets/3077956/7664308/5e4cdfbc-fb4f-11e4-8a37-7f63dc1fd5a3.jpg)

Do you have a bunch of other CSS with `.hero` or `.hero-config` classes?  Unfortunately, there's not much I can do to fix CSS conflicts for everyone (other than trying to pick reasonably unique class names that are specific to the plugin).  Perhaps you can change your `.hero` classes to something else?

You can see all of the plugin styles [here](https://github.com/jshimko/telescope-plugin-hero/blob/master/lib/client/hero.scss) or in the default content that should be in the custom CSS field in the config window.

**Comment by jshimko** [comment] 2015-05-16 02:16
Actually, that looks like none of the styles in the plugin stylesheet are loaded.  Just the ones in the config window seem to be doing something.  Are you on Windows?  I think I remember hearing that the `fourseven:scss` package had issues on Windows.  That might be what's going on.

**Comment by x5engine** [comment] 2015-05-16 02:17
yes i'm on windows and trying to inspect the styles right now

**Comment by x5engine** [comment] 2015-05-16 02:18
none of the styles are loaded as you said

**Comment by x5engine** [comment] 2015-05-16 02:20
Shouldn't the css file be inside client/scss folder ?

**Comment by x5engine** [comment] 2015-05-16 02:20
i found the error
it's 
Uncaught TypeError: Template.hero_layout.replaces is not a function
2

**Comment by jshimko** [comment] 2015-05-16 02:24
That function runs fine for me in a default Telescope install.  How did you install Telescope?  Git clone or Atmosphere?

**Comment by x5engine** [comment] 2015-05-16 02:26
downloaded the devel repo unziped then meteor
that's all
though i don't have the last 5 days commits

**Comment by jshimko** [comment] 2015-05-16 02:30
Just pushed some changes.  Try a `meteor update` and give it another test.

**Comment by x5engine** [comment] 2015-05-16 02:35
ok i just tested it and it showed a little change,
let me try it with a new fresh install

**Comment by x5engine** [comment] 2015-05-16 02:47
Still same issue, the css isn't fully loaded 

I tried it on a new devel install
![screenshot 2015-05-16 03 44 14](https://cloud.githubusercontent.com/assets/12363020/7664420/0df92fdc-fb7e-11e4-8f39-bd190f093e28.png)

**Comment by jshimko** [comment] 2015-05-16 02:49
Hmm.  Not sure what to say.  I can't reproduce your issue.  

Can you confirm whether you have `fourseven:scss` installed?  If not, can you try installing it manually?

**Comment by x5engine** [comment] 2015-05-16 02:51
in .versions i have fourseven:scss@2.1.1
but i'm also sure about this.
just flag it as unconfirmed.
thanks

**Comment by jshimko** [comment] 2015-05-16 02:56
How about if you force it to `fourseven:scss@3.0.0`?  (You can to that in the `telescope:lib` package right [here](https://github.com/TelescopeJS/Telescope/blob/devel/packages/telescope-lib/package.js#L27))

**Comment by jshimko** [comment] 2015-05-16 03:01
Nevermind. That version is apparently broken on Windows too.  See here: https://github.com/fourseven/meteor-scss/issues/83

It looks like you're probably going to have to wait until node-sass bugs are worked out for Windows users.  Sorry.  

Since this issue isn't related to my plugin, I'm closing it for now.  Let me know if you run into any other issues.  Thanks!

**Closed as completed by jshimko** 2015-05-16 03:01 UTC

**Comment by x5engine** [comment] 2015-05-16 03:02
I already have a     'fourseven:scss@2.1.1', package loaded from there

yes i'm sure it's from your plugin, i'll wait untill they fix it.
Thanks
